version: '3.8'

services:
  frontend:
    build: .
    ports:
      - 8080:5173
    volumes:
      - ./:/usr/src:cached
      - node-node_modules_data:/usr/src/node_modules:delegated
volumes:
  node_modules_data: